# tushare 网址 http://www.tushare.org

# 交易数据

## 历史行情 get_hist_data

**参数说明**
`code：`股票代码，即6位数字代码，或者指数代码（sh=上证指数 sz=深圳成指 hs300=沪深300指数 sz50=上证50 zxb=中小板 cyb=创业板）
`start：`开始日期，格式YYYY-MM-DD
`end：`结束日期，格式YYYY-MM-DD
`ktype：`数据类型，D=日k线 W=周 M=月 5=5分钟 15=15分钟 30=30分钟 60=60分钟，默认为D
`retry_count：`当网络异常后重试次数，默认为3
`pause:`重试时停顿秒数，默认为0

**返回值说明**
`date：`日期  `open：`开盘价 `high：`最高价 `close：`收盘价 `low：`最低价 `volume：`成交量 `price_change：`价格变动 `p_change：`涨跌幅 `ma5：`5日均价 `ma10：`10日均价 `ma20:`20日均价 `v_ma5:`5日均量 `v_ma10:`10日均量 `v_ma20:`20日均量 `turnover:`换手率[注：指数无此项]

**sample**
* ts.get_hist_data('600848',start='2015-01-05',end='2015-01-09')
* ts.get_hist_data('600848', ktype='W') #获取周k线数据
* ts.get_hist_data('600848', ktype='M') #获取月k线数据
* ts.get_hist_data('600848', ktype='5') #获取5分钟k线数据
* ts.get_hist_data('600848', ktype='15') #获取15分钟k线数据
* ts.get_hist_data('600848', ktype='30') #获取30分钟k线数据
* ts.get_hist_data('600848', ktype='60') #获取60分钟k线数据
* ts.get_hist_data('sh'）#获取上证指数k线数据，其它参数与个股一致，下同
* ts.get_hist_data('sz'）#获取深圳成指k线数据
* ts.get_hist_data('hs300'）#获取沪深300指数k线数据
* ts.get_hist_data('sz50'）#获取上证50指数k线数据
* ts.get_hist_data('zxb'）#获取中小板指数k线数据
* ts.get_hist_data('cyb'）#获取创业板指数k线数据

In [2]:
import tushare as ts
df=ts.get_hist_data('300096') #一次性获取全部日k线数据

In [3]:
df[["open","high","close","low","volume"]].head()

            open  high  close   low    volume
date
2019-05-27  9.39  9.72   9.68  9.28  56573.13
2019-05-24  9.22  9.46   9.40  9.22  46541.33
2019-05-23  9.60  9.64   9.22  9.22  48922.80
2019-05-22  9.64  9.72   9.60  9.30  53196.53
2019-05-21  9.55  9.74   9.57  9.42  53496.76

## 实时行情
一次性获取当前交易所有股票的行情数据（如果是节假日，即为上一交易日，结果显示速度取决于网速）

**返回值说明**
`code：`代码 `name:`名称 `changepercent:`涨跌幅 `trade:`现价 `open:`开盘价 `high:`最高价 `low:`最低价 `settlement:`昨日收盘价 `volume:`成交量 `turnoverratio:`换手率 `amount:`成交金额 `per:`市盈率 `pb:`市净率 `mktcap:`总市值 `nmc:`流通市值

**sample**
* ts.get_today_all()

In [ ]:
import tushare as ts
ts.get_today_all()

## 实时分笔
**参数说明**
`symbols：`6位数字股票代码，或者指数代码（sh=上证指数 sz=深圳成指 hs300=沪深300指数 sz50=上证50 zxb=中小板 cyb=创业板） 可输入的类型：str、list、set或者pandas的Series对象

**返回值说明**
`name`股票名字 `open`今日开盘价 `pre_close`昨日收盘价 `price`当前价格 `high`今日最高价 `low`今日最低价 `bid`竞买价，即“买一”报价 `ask`竞卖价，即“卖一”报价 `volume`成交量 maybe you need do volume/100 `amount`成交金额（元 CNY）`b1_v`委买一（笔数 bid volume）`b1_p`委买一（价格 bid price）`b2_v`“买二” `b2_p`“买二” `b3_v`“买三” `b3_p`“买三” `b4_v`“买四” `b4_p`“买四” `b5_v`“买五” `b5_p`“买五” `a1_v`委卖一（笔数 ask volume）`a1_p`委卖一（价格 ask price）`...` `date`日期；`time`时间；

**sample**
* ts.get_realtime_quotes(['600848','000980','000981'])
* ts.get_realtime_quotes(df['code'].tail(10))  #一次获取10个股票的实时分笔数据
* ts.get_realtime_quotes('sh') #上证指数
* ts.get_realtime_quotes(['sh','sz','hs300','sz50','zxb','cyb']) #上证指数 深圳成指 沪深300指数 上证50 中小板 创业板
* ts.get_realtime_quotes(['sh','600848'])

In [44]:
import tushare as ts

df = ts.get_realtime_quotes('300096') #Single stock symbol
df[['code','name','price','bid','ask','volume','amount','time']]

     code name   price     bid     ask   volume        amount      time
0  300096  易联众  10.410  10.410  10.420  9025853  89882596.020  14:18:33

## 当日历史分笔 get_today_ticks

**参数说明**
`code：`股票代码，即6位数字代码
`retry_count` int, 默认3,如遇网络等问题重复执行的次数
`pause` int, 默认 0,重复请求数据过程中暂停的秒数，防止请求间隔时间太短出现的问题

**返回值说明**
`time：`时间 `price：`当前价格 `pchange:`涨跌幅 `change：`价格变动 `volume：`成交手 `amount：`成交金额(元) `type：`买卖类型【买盘、卖盘、中性盘】

**sample**
* df=ts.get_today_ticks('300096')

In [52]:
%matplotlib inline
import tushare as ts
import matplotlib.pyplot as plt
df = ts.get_today_ticks('300096')
df.shape
#df=df.head(10)
#plt.plot(df["time"],df["change"])

(1732, 7)

## 大盘指数行情列表

**返回值说明**
`code:`指数代码 `name:`指数名称 `change:`涨跌幅 `open:`开盘点位 `preclose:`昨日收盘点位 `close:`收盘点位 `high:`最高点位 `low:`最低点位 `volume:`成交量(手) `amount:`成交金额（亿元）

**sample**
* df = ts.get_index()

In [42]:
import tushare as ts
df = ts.get_index()
df

,code,name,change,open,preclose,close,high,low,volume,amount
0,000001,上证指数,0.89,2890.2658,2892.3782,2918.1246,2918.4937,2887.0835,121204275,1240.8001
1,000002,Ａ股指数,0.89,3027.1116,3029.3235,3056.2936,3056.6813,3023.7482,121050499,1239.9151
2,000003,Ｂ股指数,0.83,290.4213,290.6511,293.0761,293.6638,290.4213,153775,0.8850
3,000008,综合指数,0.75,2789.5490,2790.9127,2811.8893,2814.0564,2786.6192,30609888,298.1995
4,000009,上证380,0.72,4589.4696,4588.1589,4621.0044,4622.7192,4584.0705,32107798,329.2081
5,000010,上证180,1.03,8084.7105,8093.3781,8176.9411,8178.7688,8074.4212,34034550,435.4501
6,000011,基金指数,0.53,5973.6302,5975.8680,6007.3508,6010.3259,5970.6115,24229264,120.5227
7,000012,国债指数,0.00,172.5180,172.5015,172.5079,172.5180,172.5044,109926,1.0765
8,000016,上证50,1.16,2719.0611,2722.3345,2753.9652,2755.9225,2716.3083,14237190,219.1604
9,000017,新综指,0.89,2440.7410,2442.5219,2464.2634,2464.5760,2438.0270,120400739,1227.7076
10,000300,沪深300,1.02,3633.0182,3637.1971,3674.1396,3674.6867,3627.7878,54278940,708.3939
11,000905,中证500,0.49,4965.5908,4962.9470,4987.1443,4992.6949,4958.6944,51641909,489.2243
12,399001,深证成指,0.83,8979.5790,8979.8260,9054.5370,9055.6660,8965.3570,16187602250,1579.2390
13,399002,深成指R,0.85,10893.4890,10891.8440,10984.4240,10985.7940,10876.2370,5965120772,689.7669
14,399003,成份Ｂ指,0.65,4803.7800,4799.9670,4831.3580,4843.2970,4795.3970,2870357,0.1568
15,399004,深证100R,1.19,4870.8160,4871.3860,4929.4730,4931.0830,4863.5930,1917161431,300.5709
16,399005,中小板指,0.73,5492.1000,5494.6140,5534.6560,5537.2730,5481.9570,1338663436,166.2018
17,399006,创业板指,0.69,1497.1170,1491.9520,1502.1940,1503.8640,1492.7490,4444621452,502.6531
18,399008,中小300,0.80,1096.4410,1096.0750,1104.8610,1105.1650,1094.4050,3475879136,341.1601
19,399100,新 指 数,0.91,7055.6150,7052.9130,7116.8640,7117.2900,7046.2590,15304853102,1549.1179
20,399101,中小板综,0.99,8711.2230,8707.4580,8793.3630,8793.8790,8699.7560,7166648602,661.0027
21,399106,深证综指,0.91,1534.4170,1533.5190,1547.5150,1547.6200,1532.4790,16187602250,1579.2390
22,399107,深证Ａ指,0.91,1604.7300,1603.7900,1618.4360,1618.5460,1602.6980,16181395253,1578.9883
23,399108,深证Ｂ指,0.71,938.0080,937.5830,944.2590,945.5260,937.6100,6206997,0.2507
24,399333,中小板R,0.74,6130.4610,6132.8130,6177.9640,6180.8860,6119.1390,1338663436,166.2018
25,399606,创业板R,0.69,1570.8490,1565.3310,1576.1760,1577.9280,1566.2660,850118676,125.1304

## 大单交易数据
**参数说明**
`code：`股票代码，即6位数字代码 `date:`日期，格式YYYY-MM-DD `vol:`手数，默认为400手，输入数值型参数 `retry_count:` int, 默认3,如遇网络等问题重复执行的次数 `pause:` int, 默认 0,重复请求数据过程中暂停的秒数，防止请求间隔时间太短出现的问题

**返回值说明**
`code：`代码 `name：`名称 `time：`时间 `price：`当前价格 `volume：`成交手 `preprice：`上一笔价格 `type：`买卖类型【买盘、卖盘、中性盘】

**sample**
* df = ts.get_sina_dd('600848', date='2015-12-24') #默认400手
* df = ts.get_sina_dd('600848', date='2015-12-24', vol=500)  #指定大于等于500手的数据

In [27]:
import tushare as ts

df = ts.get_sina_dd('300096', date='2018-12-24' ,vol=5) #默认400手
#df = ts.get_sina_dd('600848', date='2015-12-24', vol=500)  #指定大于等于500手的数据

# 分类数据
* ts.get_industry_classified() #hyfl00 行业分类
* ts.get_concept_classified()  #gnfl00  概念分类
* ts.get_area_classified()     #dyfl00 地域分类
* ts.get_sme_classified()      #zxbfl0 中小板分类
* ts.get_gem_classified()      #cybfl0 创业板分类
* ts.get_st_classified()       #ts0000 风险警示板分类
* ts.get_hs300s() # 沪深300成份股及权重
* ts.get_sz50s()  # 上证50成份股
* ts.get_zz500s() # 中证500成份股

In [29]:
import tushare as ts
ts.get_industry_classified()

        code    name c_name
0     600051    宁波联合   综合行业
1     600209    罗顿发展   综合行业
2     600212    江泉实业   综合行业
3     600256    广汇能源   综合行业
4     600576    祥源文化   综合行业
5     600603    广汇物流   综合行业
6     600614    鹏起科技   综合行业
7     600620    天宸股份   综合行业
8     600622    光大嘉宝   综合行业
9     600624    复旦复华   综合行业
10    600647    同达创业   综合行业
11    600656    退市博元   综合行业
12    600687    刚泰控股   综合行业
13    600701    工大高新   综合行业
14    600730    中国高科   综合行业
15    600770    综艺股份   综合行业
16    600777    新潮能源   综合行业
17    600800    天津磁卡   综合行业
18    600805    悦达投资   综合行业
19    600811    东方集团   综合行业
20    600832    东方明珠   综合行业
21    600846    同济科技   综合行业
22    600892    大晟文化   综合行业
23    000008    神州高铁   综合行业
24    000301    东方市场   综合行业
25    000576    广东甘化   综合行业
26    000632    三木集团   综合行业
27    000633    合金投资   综合行业
28    000652    泰达股份   综合行业
29    000701    厦门信达   综合行业
...      ...     ...    ...
2878  600983     惠而浦   家电行业
2879  603366    日出东方   家电行业
2880  603519    立霸股份   家电行业
2881  000016    深康佳Ａ   家电行业
2882  000100  TCL 集团   家电行业
2883  000333    美的集团   家电行业
2884  000418    小天鹅Ａ   家电行业
2885  000521    美菱电器   家电行业
2886  000527    美的电器   家电行业
2887  000533   万 家 乐   家电行业
2888  000541    佛山照明   家电行业
2889  000651    格力电器   家电行业
2890  000921    海信科龙   家电行业
2891  002005    德豪润达   家电行业
2892  002032   苏 泊 尔   家电行业
2893  002035    华帝股份   家电行业
2894  002076   雪 莱 特   家电行业
2895  002242    九阳股份   家电行业
2896  002260    德奥通航   家电行业
2897  002290    中科新材   家电行业
2898  002403     爱仕达   家电行业
2899  002429    兆驰股份   家电行业
2900  002473   *ST圣莱   家电行业
2901  002508    老板电器   家电行业
2902  002543    万和电气   家电行业
2903  002668    奥马电器   家电行业
2904  002677    浙江美大   家电行业
2905  002681    奋达科技   家电行业
2906  002705    新宝股份   家电行业
2907  002723     金莱特   家电行业

[2908 rows x 3 columns]

# 宏观经济

## 存款利率
**返回值说明**
`date :`变动日期 `deposit_type :`存款种类 `rate:`利率（%）

**sample**
* ts.get_deposit_rate()

In [38]:
import tushare as ts
ts.get_deposit_rate()

           date            deposit_type   rate
0    2015-10-24                定活两便(定期)     --
1    2015-10-24            定期存款整存整取(半年)   1.30
2    2015-10-24            定期存款整存整取(二年)   2.10
3    2015-10-24           定期存款整存整取(三个月)   1.10
4    2015-10-24            定期存款整存整取(三年)   2.75
5    2015-10-24            定期存款整存整取(五年)     --
6    2015-10-24            定期存款整存整取(一年)   1.50
7    2015-10-24               活期存款(不定期)   0.35
8    2015-10-24  零存整取、整存零取、存本取息定期存款(三年)   1.30
9    2015-10-24  零存整取、整存零取、存本取息定期存款(五年)     --
10   2015-10-24  零存整取、整存零取、存本取息定期存款(一年)   1.10
11   2015-10-24                通知存款(七天)   1.35
12   2015-10-24                通知存款(一天)   0.80
13   2015-10-24                协定存款(定期)   1.15
14   2015-08-26                定活两便(定期)     --
15   2015-08-26            定期存款整存整取(半年)   1.55
16   2015-08-26            定期存款整存整取(二年)   2.35
17   2015-08-26           定期存款整存整取(三个月)   1.35
18   2015-08-26            定期存款整存整取(三年)   3.00
19   2015-08-26            定期存款整存整取(五年)     --
20   2015-08-26            定期存款整存整取(一年)   1.75
21   2015-08-26               活期存款(不定期)   0.35
22   2015-08-26  零存整取、整存零取、存本取息定期存款(三年)   1.55
23   2015-08-26  零存整取、整存零取、存本取息定期存款(五年)     --
24   2015-08-26  零存整取、整存零取、存本取息定期存款(一年)   1.35
25   2015-08-26                通知存款(七天)   1.35
26   2015-08-26                通知存款(一天)   0.80
27   2015-08-26                协定存款(定期)   1.15
28   2015-06-28                定活两便(定期)     --
29   2015-06-28            定期存款整存整取(半年)   1.80
..          ...                     ...    ...
516  1990-08-21                通知存款(一天)     --
517  1990-08-21                协定存款(定期)     --
518  1990-04-15                定活两便(定期)     --
519  1990-04-15            定期存款整存整取(半年)   7.74
520  1990-04-15            定期存款整存整取(二年)  11.00
521  1990-04-15           定期存款整存整取(三个月)   6.30
522  1990-04-15            定期存款整存整取(三年)  11.88
523  1990-04-15            定期存款整存整取(五年)  13.68
524  1990-04-15            定期存款整存整取(一年)  10.08
525  1990-04-15               活期存款(不定期)   2.88
526  1990-04-15  零存整取、整存零取、存本取息定期存款(三年)     --
527  1990-04-15  零存整取、整存零取、存本取息定期存款(五年)     --
528  1990-04-15  零存整取、整存零取、存本取息定期存款(一年)     --
529  1990-04-15                通知存款(七天)     --
530  1990-04-15                通知存款(一天)     --
531  1990-04-15                协定存款(定期)     --
532  1989-02-01                定活两便(定期)     --
533  1989-02-01            定期存款整存整取(半年)   9.00
534  1989-02-01            定期存款整存整取(二年)  12.20
535  1989-02-01           定期存款整存整取(三个月)   7.56
536  1989-02-01            定期存款整存整取(三年)  13.14
537  1989-02-01            定期存款整存整取(五年)  14.94
538  1989-02-01            定期存款整存整取(一年)  11.34
539  1989-02-01               活期存款(不定期)   2.88
540  1989-02-01  零存整取、整存零取、存本取息定期存款(三年)     --
541  1989-02-01  零存整取、整存零取、存本取息定期存款(五年)     --
542  1989-02-01  零存整取、整存零取、存本取息定期存款(一年)     --
543  1989-02-01                通知存款(七天)     --
544  1989-02-01                通知存款(一天)     --
545  1989-02-01                协定存款(定期)     --

[546 rows x 3 columns]

## 贷款利率
**返回值说明**
`date :`执行日期 `loan_type :`存款种类 `rate:`利率（%）

**sample**
* ts.get_loan_rate()

In [37]:
import tushare as ts
ts.get_loan_rate()

           date            loan_type   rate
0    2015-10-24          短期贷款(六个月以内)   4.35
1    2015-10-24         短期贷款(六个月至一年)   4.35
2    2015-10-24          中长期贷款(三至五年)   4.75
3    2015-10-24          中长期贷款(五年以上)   4.90
4    2015-10-24          中长期贷款(一至三年)   4.75
5    2015-10-24               贴现(贴现)     --
6    2015-10-24         优惠贷款(扶贫贴息贷款)     --
7    2015-10-24     优惠贷款(老少边穷发展经济贷款)     --
8    2015-10-24     优惠贷款(民政部门福利工厂贷款)     --
9    2015-10-24  优惠贷款(民族贸易及民族用品生产贷款)     --
10   2015-10-24       优惠贷款(贫困县办工业贷款)     --
11   2015-10-24      个人住房商业贷款(六个月以内)   3.92
12   2015-10-24     个人住房商业贷款(六个月至一年)   3.92
13   2015-10-24       个人住房商业贷款(三至五年)   4.28
14   2015-10-24       个人住房商业贷款(五年以上)   4.41
15   2015-10-24       个人住房商业贷款(一至三年)   4.28
16   2015-10-24      个人住房公积金贷款(五年以上)   3.25
17   2015-10-24      个人住房公积金贷款(五年以下)   2.75
18   2015-09-06            再贴现(再贴现率)   2.25
19   2015-08-26          短期贷款(六个月以内)   4.60
20   2015-08-26         短期贷款(六个月至一年)   4.60
21   2015-08-26          中长期贷款(三至五年)   5.00
22   2015-08-26          中长期贷款(五年以上)   5.15
23   2015-08-26          中长期贷款(一至三年)   5.00
24   2015-08-26               贴现(贴现)     --
25   2015-08-26         优惠贷款(扶贫贴息贷款)     --
26   2015-08-26     优惠贷款(老少边穷发展经济贷款)     --
27   2015-08-26     优惠贷款(民政部门福利工厂贷款)     --
28   2015-08-26  优惠贷款(民族贸易及民族用品生产贷款)     --
29   2015-08-26       优惠贷款(贫困县办工业贷款)     --
..          ...                  ...    ...
770  1993-05-15      个人住房公积金贷款(五年以上)     --
771  1993-05-15      个人住房公积金贷款(五年以下)     --
772  1993-05-12         特种贷款(特种贷款利率)  11.25
773  1991-04-21          短期贷款(六个月以内)   8.10
774  1991-04-21         短期贷款(六个月至一年)   8.64
775  1991-04-21          中长期贷款(三至五年)   9.54
776  1991-04-21          中长期贷款(五年以上)   9.72
777  1991-04-21          中长期贷款(一至三年)   9.00
778  1991-04-21               贴现(贴现)     --
779  1991-04-21         优惠贷款(扶贫贴息贷款)   2.88
780  1991-04-21     优惠贷款(老少边穷发展经济贷款)   5.76
781  1991-04-21     优惠贷款(民政部门福利工厂贷款)   7.20
782  1991-04-21  优惠贷款(民族贸易及民族用品生产贷款)   5.76
783  1991-04-21       优惠贷款(贫困县办工业贷款)   5.76
784  1991-04-21      个人住房商业贷款(六个月以内)   7.29
785  1991-04-21     个人住房商业贷款(六个月至一年)   7.78
786  1991-04-21       个人住房商业贷款(三至五年)   8.59
787  1991-04-21       个人住房商业贷款(五年以上)   8.75
788  1991-04-21       个人住房商业贷款(一至三年)   8.10
789  1991-04-21      个人住房公积金贷款(五年以上)     --
790  1991-04-21      个人住房公积金贷款(五年以下)     --
791  1991-04-21         特种贷款(特种贷款利率)   9.72
792  1990-08-21          短期贷款(六个月以内)   8.64
793  1990-08-21         短期贷款(六个月至一年)   9.36
794  1990-08-21          中长期贷款(三至五年)  10.80
795  1990-08-21          中长期贷款(五年以上)  11.16
796  1990-08-21          中长期贷款(一至三年)  10.08
797  1990-08-21               贴现(贴现)     --
798  1990-08-21         优惠贷款(扶贫贴息贷款)     --
799  1990-08-21     优惠贷款(老少边穷发展经济贷款)     --

[800 rows x 3 columns]

## 存款准备金率

**返回值说明**
`date :`变动日期 `before :`调整前存款准备金率(%) `now:`调整后存款准备金率(%) `changed:`调整幅度(%)

**sample**
* ts.get_rrr()

In [39]:
import tushare as ts
ts.get_rrr()

          date before    now changed
0   2019-01-25  13.50  13.00   -0.50
1   2019-01-15  14.00  13.50   -0.50
2   2018-10-15  15.00  14.00   -1.00
3   2018-07-05  15.50  15.00   -0.50
4   2018-04-25  16.50  15.50   -1.00
5   2016-03-01  17.00  16.50   -0.50
6   2015-10-24  17.50  17.00   -0.50
7   2015-09-06  18.00  17.50   -0.50
8   2015-06-28  18.50  18.00   -0.50
9   2015-04-20  19.50  18.50   -1.00
10  2015-02-05  20.00  19.50   -0.50
11  2012-05-18  20.50  20.00   -0.50
12  2012-02-24  21.00  20.50   -0.50
13  2011-12-05  21.50  21.00   -0.50
14  2011-06-20  21.00  21.50    0.50
15  2011-05-18  20.50  21.00    0.50
16  2011-04-21  20.00  20.50    0.50
17  2011-03-25  19.50  20.00    0.50
18  2011-02-24  19.00  19.50    0.50
19  2011-01-20  18.50  19.00    0.50
20  2010-12-20  18.00  18.50    0.50
21  2010-11-29  17.50  18.00    0.50
22  2010-11-16  17.00  17.50    0.50
23  2010-05-10  16.50  17.00    0.50
24  2010-02-25  16.00  16.50    0.50
25  2010-01-18  15.50  16.00    0.50
26  2008-12-25  16.00  15.50   -0.50
27  2008-12-05  17.00  16.00   -1.00
28  2008-10-15  17.50  17.00   -0.50
29  2008-09-25  17.50  17.50    0.00
30  2008-06-25  17.00  17.50    0.50
31  2008-06-15  16.50  17.00    0.50
32  2008-05-20  16.00  16.50    0.50
33  2008-04-25  15.50  16.00    0.50
34  2008-03-25  15.00  15.50    0.50
35  2008-01-25  14.50  15.00    0.50
36  2007-12-25  13.50  14.50    1.00
37  2007-11-26  13.00  13.50    0.50
38  2007-10-25  12.50  13.00    0.50
39  2007-09-25  12.00  12.50    0.50
40  2007-08-15  11.50  12.00    0.50
41  2007-06-05  11.00  11.50    0.50
42  2007-05-15  10.50  11.00    0.50
43  2007-04-16  10.00  10.50    0.50
44  2007-02-25   9.50  10.00    0.50
45  2007-01-15   9.00   9.50    0.50
46  2006-11-15   8.50   9.00    0.50
47  2006-08-15   8.00   8.50    0.50
48  2006-07-05   7.50   8.00    0.50
49  2004-04-25   7.00   7.50    0.50
50  2003-09-21   6.00   7.00    1.00
51  1999-11-21   8.00   6.00   -2.00
52  1998-03-21  13.00   8.00   -5.00
53  1988-09-30  12.00  13.00    1.00
54  1987-12-31  10.00  12.00    2.00
55  1985-12-31     --  10.00      --

## 货币供应量

**返回值说明**
`month :`统计时间 `m2 :`货币和准货币（广义货币M2）(亿元) `m2_yoy:`货币和准货币（广义货币M2）同比增长(%)  `m1:`货币(狭义货币M1)(亿元) `m1_yoy:`货币(狭义货币M1)同比增长(%) `m0:`流通中现金(M0)(亿元) `m0_yoy:`流通中现金(M0)同比增长(%) `cd:`活期存款(亿元)
 `cd_yoy:`活期存款同比增长(%) `qm:`准货币(亿元) `qm_yoy:`准货币同比增长(%) `ftd:`定期存款(亿元) `ftd_yoy:`定期存款同比增长(%) `sd:`储蓄存款(亿元) `sd_yoy:`储蓄存款同比增长(%) `rests:`其他存款(亿元) `rests_yoy:`其他存款同比增长(%)

**sample**
* ts.get_money_supply()

In [ ]:
import tushare as ts
ts.get_money_supply()

## 货币供应量(年底余额)

**返回值说明**
`year :`统计年度 `m2 :`货币和准货币(亿元) `m1:`货币(亿元) `m0:`流通中现金(亿元) `cd:`活期存款(亿元) `qm:`准货币(亿元) `ftd:`定期存款(亿元) `sd:`储蓄存款(亿元) `rests:`其他存款(亿元)

**sample**
* ts.get_money_supply_bal()

In [ ]:
import tushare as ts
ts.get_money_supply_bal()

## 国内生产总值(年度)
**返回值说明**
`year :`统计年度 `gdp :`国内生产总值(亿元) `pc_gdp :`人均国内生产总值(元) `gnp :`国民生产总值(亿元) `pi :`第一产业(亿元) `si :`第二产业(亿元) `industry :`工业(亿元) `cons_industry :`建筑业(亿元) `ti :`第三产业(亿元) `trans_industry :`交通运输仓储邮电通信业(亿元) `lbdy :`批发零售贸易及餐饮业(亿元)

**sample**
* ts.get_gdp_year()

In [31]:
import tushare as ts
ts.get_gdp_year()

,year,gdp,pc_gdp,gnp,pi,si,industry,cons_industry,ti,trans_industry,lbdy
0,2018,900309.00,64644.00,NaN,64734.00,366001.00,305160.00,61808.00,469575.00,40550.00,100224.00
1,2017,820754.00,59660.00,NaN,62100.00,332743.00,278328.00,55314.00,425912.00,37173.00,92348.00
2,2016,743585.50,53935.00,NaN,63672.80,296547.70,247877.70,49702.90,383365.00,33058.80,84648.80
3,2015,689052.10,50251.00,NaN,60862.10,282040.30,236506.30,46626.70,346149.70,30487.80,78340.40
4,2014,643974.00,47203.00,NaN,58343.50,277571.80,233856.40,44880.50,308058.60,28500.90,73582.00
5,2013,588018.80,43852.00,NaN,55321.70,261956.10,210689.42,38995.00,275887.00,27282.93,66512.40
6,2012,534123.00,40007.00,NaN,50892.70,240200.40,199670.66,35491.34,243030.00,24660.00,60295.21
7,2011,484123.50,35197.79,NaN,46153.30,223390.30,188470.15,31942.66,214579.90,22432.84,52903.35
8,2010,401202.00,29992.00,403260.00,40533.60,187581.42,160867.01,26714.41,173087.00,18968.48,43814.55
9,2009,340902.80,25608.00,341401.50,35226.00,157638.80,135239.90,22398.80,148038.00,16727.10,36102.70
10,2008,314045.40,23708.00,315274.70,33702.00,149003.40,130260.20,18743.20,131340.00,16362.50,32798.40
11,2007,265810.30,20169.00,266411.00,28627.00,125831.40,110534.90,15296.50,111351.90,14601.00,26485.90
12,2006,216314.43,16499.70,215904.41,24040.00,103719.54,91310.94,12408.60,88554.88,12182.98,21323.31
13,2005,184937.37,14185.36,183617.37,22420.00,87598.09,77230.78,10367.32,74919.28,10666.16,18161.89
14,2004,159878.34,12335.58,159453.60,21412.73,73904.31,65210.03,8694.28,64561.29,9304.39,16118.65
15,2003,135822.76,10541.97,134976.97,17381.72,62436.31,54945.53,7490.78,56004.73,7913.19,14295.53
16,2002,120332.69,9398.05,119095.69,16537.02,53896.77,47431.31,6465.46,49898.90,7492.95,12720.10
17,2001,109655.17,8621.71,108068.22,15781.27,49512.29,43580.62,5931.67,44361.61,6870.25,11519.54
18,2000,99214.55,7857.68,98000.45,14944.72,45555.88,40033.59,5522.29,38713.95,6160.95,10304.85
19,1999,89677.10,7159.00,88479.20,14770.00,41033.60,35861.50,5172.10,33873.40,5175.20,9432.30
20,1998,84402.30,6796.00,83024.30,14817.60,39004.20,34018.40,4985.80,30580.50,4660.90,8700.10
21,1997,78973.00,6420.00,78060.80,14441.90,37543.00,32921.40,4621.60,26988.10,4148.60,7888.70
22,1996,71176.60,5846.00,70142.50,14015.40,33835.00,29447.60,4387.40,23326.20,3782.20,6936.50
23,1995,60793.70,5046.00,59810.50,12135.80,28679.50,24950.60,3728.80,19978.50,3244.30,5978.70
24,1994,48197.90,4044.00,48108.50,9572.70,22445.40,19480.70,2964.70,16179.80,2787.90,4781.90
25,1993,35333.90,2998.00,35260.00,6963.80,16454.40,14188.00,2266.50,11915.70,2174.00,3528.70
26,1992,26923.50,2311.00,26937.30,5866.60,11699.50,10284.50,1415.00,9357.40,1689.00,2989.60
27,1991,21781.50,1893.00,21826.20,5342.20,9102.20,8087.10,1015.10,7337.10,1420.30,2276.90
28,1990,18667.80,1644.00,18718.30,5062.00,7717.40,6858.00,859.40,5888.40,1167.00,1570.80
29,1989,16992.30,1519.00,17000.90,4265.90,7278.00,6484.00,794.00,5448.40,812.70,1813.60
...,...,...,...,...,...,...,...,...,...,...,...
37,1981,4891.60,492.00,4889.50,1559.50,2255.50,2048.40,207.10,1076.60,220.70,285.20
38,1980,4545.60,463.00,4545.60,1371.60,2192.00,1996.50,195.50,982.00,213.40,241.20
39,1979,4062.60,419.00,4062.60,1270.20,1913.50,1769.70,143.80,878.90,193.70,244.90
40,1978,3645.20,381.00,3645.20,1027.50,1745.20,1607.00,138.20,872.50,182.00,286.90
41,1977,3201.90,339.00,3201.90,942.10,1509.10,1372.40,136.70,750.70,156.90,213.80
42,1976,2943.70,316.00,2943.70,967.00,1337.20,1204.60,132.60,639.50,139.60,147.20
43,1975,2997.30,327.00,2997.30,971.10,1370.50,1244.90,125.60,655.70,141.60,175.80
44,1974,2789.90,310.00,2789.90,945.20,1192.00,1083.60,108.40,652.70,126.10,206.60
45,1973,2720.90,309.00,2720.90,907.50,1173.00,1072.50,100.50,640.40,125.50,211.00
46,1972,2518.10,292.00,2518.10,827.40,1084.20,989.90,94.30,606.50,118.00,194.30
47,1971,2426.40,288.00,2426.40,826.30,1022.80,926.60,96.20,577.30,108.40,178.30
48,1970,2252.70,275.00,2252.70,793.30,912.20,828.10,84.10,547.20,100.20,178.10
49,1969,1937.90,243.00,1937.90,736.20,689.10,626.10,63.00,512.60,84.90,163.60
50,1968,1723.10,222.00,1723.10,726.30,537.30,490.30,47.00,459.50,70.50,138.90
51,1967,1773.90,235.00,1773.90,714.20,602.80,544.90,57.90,456.90,72.30,153.50
52,1966,1868.00,254.00,1868.00,702.20,709.50,648.60,60.90,456.30,85.10,148.10
53,1965,1716.10,240.00,1716.10,651.10,602.20,546.50,55.70,462.80,77.40,118.30
54,1964,1454.00,208.00,1454.00,559.00,513.50,461.10,52.40,381.50,58.40,94.00
55,1963,1233.30,181.00,1233.30,497.50,407.60,365.60,42.00,328.20,55.00,76.10
56,1962,1149.30,173.00,1149.30,453.10,359.30,325.40,33.90,336.90,57.40,80.50
57,1961,1220.00,185.00,1220.00,441.10,388.90,362.10,26.80,390.00,69.20,110.80
58,1960,1457.00,218.00,1457.00,340.70,648.20,568.20,80.00,468.10,104.00,133.10
59,1959,1439.00,216.00,1439.00,383.80,615.50,538.50,77.00,439.70,94.00,145.70
60,1958,1307.00,200.00,1307.00,445.90,483.50,414.50,69.00,377.60,71.00,136.60
61,1957,1068.00,168.00,1068.00,430.00,317.00,271.00,46.00,321.00,49.00,133.00
62,1956,1028.00,165.00,1028.00,443.90,280.70,224.70,56.00,303.40,46.00,131.40
63,1955,910.00,150.00,910.00,421.00,222.20,191.20,31.00,266.80,39.00,119.80
64,1954,859.00,144.00,859.00,392.00,211.70,184.70,27.00,255.30,38.00,120.30
65,1953,824.00,142.00,824.00,378.00,192.50,163.50,29.00,253.50,35.00,115.50
66,1952,679.00,119.00,679.00,342.90,141.80,119.80,22.00,194.30,29.00,80.30

## 国内生产总值(季度)
**返回值说明**
`quarter :`季度 `gdp :`国内生产总值(亿元) `gdp_yoy :`国内生产总值同比增长(%) `pi :`第一产业增加值(亿元) `pi_yoy:`第一产业增加值同比增长(%) `si :`第二产业增加值(亿元) `si_yoy :`第二产业增加值同比增长(%) `ti :`第三产业增加值(亿元) `ti_yoy :`第三产业增加值同比增长(%)

**sample**
* ts.get_gdp_quarter()

In [30]:
import tushare as ts

ts.get_gdp_quarter()

,quarter,gdp,gdp_yoy,pi,pi_yoy,si,si_yoy,ti,ti_yoy
0,2019.1,213433.0,6.40,8769.0,2.7,82346.0,6.1,122317.0,7.0
1,2018.4,900309.0,6.60,64734.0,3.5,366001.0,5.8,469575.0,7.6
2,2018.3,650899.0,6.70,42173.0,3.4,262953.0,5.8,345773.0,7.7
3,2018.2,418961.0,6.80,22087.0,3.2,169299.0,6.1,227576.0,7.6
4,2018.1,198783.0,6.80,8904.0,3.2,77451.0,6.3,112428.0,7.5
5,2017.4,820754.0,6.80,62100.0,4.0,332743.0,5.9,425912.0,7.9
6,2017.3,593288.0,6.90,41229.0,3.7,238109.0,6.3,313951.0,7.8
7,2017.2,381490.0,6.90,21987.0,3.5,152987.0,6.4,206516.0,7.7
8,2017.1,180683.0,6.90,8654.0,3.0,70005.0,6.4,102024.0,7.7
9,2016.4,743585.5,6.70,63670.7,3.3,296236.0,6.1,384220.5,7.8
10,2016.3,532434.0,6.70,40665.7,3.5,210534.5,6.1,281645.7,7.6
11,2016.2,342071.4,6.70,22096.7,3.1,134977.6,6.1,185242.1,7.5
12,2016.1,161456.3,6.66,8803.0,2.9,61325.0,5.9,91444.7,7.6
13,2015.4,689052.1,6.90,60862.1,3.9,282040.3,6.1,346149.7,8.3
14,2015.3,496200.2,7.00,38344.6,3.8,203537.4,6.1,254318.1,8.4
15,2015.2,319489.7,7.00,20257.1,3.5,131872.1,6.2,167360.5,8.3
16,2015.1,150986.7,7.00,7770.4,3.1,60724.7,6.3,82491.6,8.0
17,2014.4,643974.0,7.30,58343.5,4.1,277571.8,7.4,308058.6,7.8
18,2014.3,462791.5,7.30,36820.9,4.1,199787.4,7.6,226183.3,7.6
19,2014.2,297079.7,7.40,19145.3,3.7,128762.6,7.7,149171.7,7.6
20,2014.1,140618.3,7.30,7491.9,3.2,59221.5,7.6,73905.0,7.6
21,2013.4,595244.4,7.80,55329.1,3.8,261956.1,8.0,277959.3,8.3
22,2013.3,426619.3,7.80,34605.0,3.3,187743.6,7.9,204270.7,8.4
23,2013.2,273713.9,7.70,18011.9,2.8,120993.6,7.7,134708.4,8.3
24,2013.1,129747.0,7.90,7169.6,3.0,55862.3,7.8,66715.0,8.4
25,2012.4,540367.4,7.90,50902.3,4.5,244643.3,8.4,244821.9,8.0
26,2012.3,387898.6,7.80,32163.8,4.2,176008.8,8.3,179726.0,7.8
27,2012.2,249276.4,7.90,16966.8,4.3,113751.5,8.7,118558.0,7.6
28,2012.1,117593.9,8.10,6687.0,3.7,52317.4,9.5,58589.5,7.3
29,2011.4,472882.0,9.30,47486.0,4.3,220413.0,10.3,204983.0,9.4
...,...,...,...,...,...,...,...,...,...
119,1981.4,4891.6,5.20,1559.5,7.0,2255.5,1.9,1076.6,10.4
120,1980.4,4545.6,7.80,1371.6,-1.5,2192.0,13.6,982.0,6.0
121,1979.4,4062.6,7.60,1270.2,6.1,1913.5,8.2,878.9,7.9
122,1978.4,3645.2,11.70,1027.5,4.1,1745.2,15.0,872.5,13.8
123,1977.4,3201.9,7.60,942.1,-2.2,1509.1,13.3,750.7,9.5
124,1976.4,2943.7,-1.60,967.0,-1.8,1337.2,-2.5,639.5,0.4
125,1975.4,2997.3,8.70,971.1,2.0,1370.5,15.8,655.7,4.9
126,1974.4,2789.9,2.30,945.2,4.1,1192.0,1.4,652.7,1.6
127,1973.4,2720.9,7.90,907.5,9.0,1173.0,8.3,640.4,5.5
128,1972.4,2518.1,3.80,827.4,-0.9,1084.2,6.7,606.5,5.0
129,1971.4,2426.4,7.00,826.3,1.9,1022.8,12.3,577.3,5.8
130,1970.4,2252.7,19.40,793.3,7.7,912.2,34.8,547.2,7.1
131,1969.4,1937.9,16.90,736.2,0.8,689.1,33.1,512.6,13.3
132,1968.4,1723.1,-4.10,726.3,-1.6,537.3,-9.2,459.5,0.6
133,1967.4,1773.9,-5.70,714.2,1.9,602.8,-14.3,456.9,0.5
134,1966.4,1868.0,10.70,702.2,7.2,709.5,22.4,456.3,-1.8
135,1965.4,1716.1,17.00,651.1,9.7,602.2,24.2,462.8,15.8
136,1964.4,1454.0,18.30,559.0,12.9,513.5,25.6,381.5,15.5
137,1963.4,1233.3,10.20,497.5,11.3,407.6,14.5,328.2,4.4
138,1962.4,1149.3,-5.60,453.1,4.5,359.3,-10.8,336.9,-9.2
139,1961.4,1220.0,-27.30,441.1,1.4,388.9,-42.1,390.0,-25.7
140,1960.4,1457.0,-0.30,340.7,-16.4,648.2,5.6,468.1,4.8
141,1959.4,1439.0,8.80,383.8,-15.9,615.5,25.8,439.7,15.2
142,1958.4,1307.0,21.30,445.9,0.4,483.5,52.9,377.6,17.9
143,1957.4,1068.0,5.10,430.0,3.1,317.0,8.0,321.0,4.8
144,1956.4,1028.0,15.00,443.9,4.7,280.7,34.5,303.4,14.1
145,1955.4,910.0,6.80,421.0,7.9,222.2,7.6,266.8,4.6
146,1954.4,859.0,4.20,392.0,1.7,211.7,15.7,255.3,-0.6
147,1953.4,824.0,15.60,378.0,1.9,192.5,35.8,253.5,27.3
148,1952.4,679.0,NaN,342.9,NaN,141.8,NaN,194.3,NaN

## 三大需求对GDP贡献

**返回值说明**
`year :`统计年度 `end_for :`最终消费支出贡献率(%) `for_rate :`最终消费支出拉动(百分点) `asset_for :`资本形成总额贡献率(%) `asset_rate:`资本形成总额拉动(百分点) `goods_for :`货物和服务净出口贡献率(%) `goods_rate :`货物和服务净出口拉动(百分点)

**sample**
* ts.get_gdp_for()

In [32]:
import tushare as ts
ts.get_gdp_for()

    year  end_for  for_rate  asset_for  asset_rate  goods_for  goods_rate
0   2017     58.8       4.1       32.1         2.2        9.1         0.6
1   2016     66.5       4.5       43.1         2.9       -9.6        -0.7
2   2015     59.7       4.1       41.6         2.9       -1.3        -0.1
3   2014     48.8       3.6       46.9         3.4        4.3         0.3
4   2013     48.2       3.6       54.2         4.3       -2.3        -0.1
5   2012     56.7       4.3       42.0         3.4        1.7         0.2
6   2011     61.9       5.9       46.2         4.4       -8.1        -0.8
7   2010     46.9       4.8       66.0         7.1      -11.2        -1.3
8   2009     56.1       5.3       86.5         8.1      -42.6        -4.0
9   2008     44.2       4.3       53.2         5.1        2.6         0.3
10  2007     45.3       6.4       44.1         6.3       10.6         1.5
11  2006     42.0       5.3       42.9         5.5       15.1         1.9
12  2005     54.4       6.2       33.1         3.8       12.5         1.4
13  2004     42.6       4.3       61.6         6.2       -4.2        -0.4
14  2003     35.4       3.6       70.0         7.0       -5.4        -0.6
15  2002     43.9       5.1       48.5         3.6        4.6         0.4
16  2001     49.0       4.1       64.0         5.3      -13.0        -1.1
17  2000     78.1       6.6       22.4         1.9       -0.5         NaN
18  1999     74.7       5.7       23.7         1.8        1.6         0.1
19  1998     57.1       4.4       26.4         2.1       16.5         1.3
20  1997     37.0       3.4       18.6         1.7       44.4         4.2
21  1996     60.1       6.0       34.3         3.4        5.6         0.6
22  1995     44.7       4.9       55.0         6.0        0.3         NaN
23  1994     30.2       4.0       43.8         5.7       26.0         3.4
24  1993     59.5       8.3       78.6        11.0      -38.1        -5.3
25  1992     72.5      10.3       34.2         4.9       -6.8        -1.0
26  1991     65.1       6.0       24.3         2.2       10.6         1.0
27  1990     47.8       1.8        1.8         0.1       50.4         1.9
28  1989     39.6       1.6       16.4         0.7       44.0         1.8
29  1988     49.6       5.6       39.4         4.5       11.0         1.2
30  1987     50.3       5.8       23.5         2.7       26.2         3.1
31  1986     45.0       4.0       23.2         2.0       31.8         2.8
32  1985     85.5      11.5       80.9        10.9      -66.4        -8.9
33  1984     69.3      10.5       40.5         6.2       -9.8        -1.5
34  1983     74.1       8.1       40.4         4.4      -14.5        -1.6
35  1982     64.7       5.9       23.8         2.2       11.5         1.0
36  1981     93.4       4.9       -4.3        -0.2       10.9         0.5
37  1980     71.8       5.6       26.4         2.1        1.8         0.1
38  1979     87.3       6.6       15.4         1.2       -2.7        -0.2
39  1978     39.4       4.6       66.0         7.7       -5.4        -0.6

## 三大产业对GDP拉动

**返回值说明**
`year :`统计年度 `gdp_yoy :`国内生产总值同比增长(%) `pi :`第一产业拉动率(%) `si :`第二产业拉动率(%) `industry:`其中工业拉动(%) `ti :`第三产业拉动率(%)

**sample**
* ts.get_gdp_pull()

In [33]:
import tushare as ts
ts.get_gdp_pull()

    year  gdp_yoy   pi   si  industry   ti
0   2018      6.6  NaN  NaN       NaN  NaN
1   2017      6.9  0.3  2.5       2.2  4.0
2   2016      6.7  0.3  2.6       2.1  3.9
3   2015      6.9  0.3  2.9       2.4  3.7
4   2014      7.3  0.3  3.5       2.9  3.5
5   2013      7.8  0.3  3.8       3.1  3.7
6   2012      7.9  0.4  3.9       3.3  3.5
7   2011      9.5  0.4  5.0       4.4  4.2
8   2010     10.6  0.4  6.1       5.3  4.2
9   2009      9.2  0.4  4.9       3.8  4.1
10  2008      9.6  0.5  4.7       4.2  4.5
11  2007     14.2  0.4  7.1       6.2  6.7
12  2006     12.7  0.6  6.3       5.4  5.8
13  2005     11.3  0.6  5.8       4.9  5.0
14  2004     10.1  0.7  5.2       4.8  4.1
15  2003     10.0  0.3  5.8       5.2  3.9
16  2002      9.1  0.4  4.5       4.0  4.2
17  2001      8.3  0.4  3.9       3.5  4.1
18  2000      8.4  0.4  5.1       4.8  3.1
19  1999      7.6  0.4  4.4       4.2  2.8
20  1998      7.8  0.6  4.8       4.3  2.4
21  1997      9.3  0.6  5.6       5.4  3.1
22  1996     10.0  1.0  6.3       5.9  2.7
23  1995     10.9  1.0  7.0       6.4  2.9
24  1994     13.1  0.9  8.9       8.2  3.3
25  1993     14.0  1.1  9.2       8.3  3.7
26  1992     14.2  1.2  9.2       8.2  3.8
27  1991      9.2  0.6  5.8       5.3  2.8
28  1990      3.8  1.6  1.6       1.5  0.6

## 三大产业贡献率

**返回值说明**
`year :`统计年度 `gdp_yoy :`国内生产总值 `pi :`第一产业献率(%) `si :`第二产业献率(%) `industry:`其中工业献率(%) `ti :`第三产业献率(%)

**sample**
* ts.get_gdp_contrib()

In [34]:
import tushare as ts
ts.get_gdp_contrib()

    year  gdp_yoy    pi    si  industry    ti
0   2017    100.0   4.9  36.3      31.9  58.8
1   2016    100.0   4.3  38.2      30.7  57.5
2   2015    100.0   4.6  42.4      35.4  52.9
3   2014    100.0   4.7  47.8      39.2  47.5
4   2013    100.0   4.3  48.5      40.5  47.2
5   2012    100.0   5.2  49.9      41.9  44.9
6   2011    100.0   4.2  52.0      45.9  43.8
7   2010    100.0   3.6  57.4      49.6  39.0
8   2009    100.0   4.0  52.3      40.7  43.7
9   2008    100.0   5.2  48.6      43.4  46.2
10  2007    100.0   2.7  50.1      43.8  47.3
11  2006    100.0   4.4  49.7      42.3  45.9
12  2005    100.0   5.2  50.5      43.1  44.3
13  2004    100.0   7.3  51.8      47.6  40.8
14  2003    100.0   3.1  57.9      51.6  39.0
15  2002    100.0   4.1  49.4      44.3  46.5
16  2001    100.0   4.6  46.4      42.0  49.0
17  2000    100.0   4.1  59.6      56.9  36.2
18  1999    100.0   6.0  57.8      55.0  36.2
19  1998    100.0   7.6  60.9      55.4  31.5
20  1997    100.0   6.8  59.7      58.3  33.5
21  1996    100.0   9.6  62.9      58.5  27.5
22  1995    100.0   9.1  64.3      58.5  26.6
23  1994    100.0   6.6  67.9      62.6  25.5
24  1993    100.0   7.9  65.5      59.1  26.6
25  1992    100.0   8.4  64.5      57.6  27.1
26  1991    100.0   7.1  62.8      58.0  30.1
27  1990    100.0  41.7  41.0      39.7  17.3

## 居民消费价格指数

**返回值说明**
`month :`统计月份 `cpi :`价格指数

**sample**
* ts.get_cpi()

In [35]:
import tushare as ts
ts.get_cpi()

       month     cpi
0     2019.4  102.54
1     2019.3  102.28
2     2019.2  101.49
3     2019.1  101.74
4    2018.12  101.86
5    2018.11  102.18
6    2018.10  102.54
7     2018.9  102.50
8     2018.8  102.30
9     2018.7  102.10
10    2018.6  101.85
11    2018.5  101.75
12    2018.4  101.80
13    2018.3  102.06
14    2018.2  102.90
15    2018.1  101.47
16   2017.12  102.00
17   2017.11  101.73
18   2017.10  101.87
19    2017.9  101.60
20    2017.8  101.77
21    2017.7  101.40
22    2017.6  101.50
23    2017.5  101.52
24    2017.4  101.17
25    2017.3  100.92
26    2017.2  100.80
27    2017.1  102.55
28   2016.12  102.08
29   2016.11  102.25
..       ...     ...
322   1992.6  104.80
323   1992.5  104.70
324   1992.4  107.10
325   1992.3  105.30
326   1992.2  105.30
327   1992.1  105.50
328  1991.12  104.50
329  1991.11  104.40
330  1991.10  104.80
331   1991.9  104.50
332   1991.8  104.90
333   1991.7  104.70
334   1991.6  104.40
335   1991.5  103.60
336   1991.4  101.30
337   1991.3  101.60
338   1991.2  101.00
339   1991.1  102.20
340  1990.12  104.30
341  1990.11  103.70
342  1990.10  103.10
343   1990.9  102.90
344   1990.8  102.50
345   1990.7  101.10
346   1990.6  101.10
347   1990.5  102.70
348   1990.4  103.20
349   1990.3  103.40
350   1990.2  104.40
351   1990.1  104.30

[352 rows x 2 columns]

## 工业品出厂价格指数

**返回值说明**
`month :`统计月份 `ppiip :`工业品出厂价格指数 `ppi :`生产资料价格指数 `qm:`采掘工业价格指数 `rmi:`原材料工业价格指数 `pi:`加工工业价格指数 `cg:`生活资料价格指数 `food:`食品类价格指数 `clothing:`衣着类价格指数 `roeu:`一般日用品价格指数 `dcg:`耐用消费品价格指数

**sample**
* ts.get_ppi()

In [36]:
import tushare as ts
ts.get_ppi()

,month,ppiip,ppi,qm,rmi,pi,cg,food,clothing,roeu,dcg
0,2019.4,100.90,100.9,105.30,100.00,100.90,100.90,101.90,101.70,100.30,99.40
1,2019.3,100.40,100.3,104.20,99.40,100.40,100.50,101.20,101.70,100.30,99.30
2,2019.2,100.10,99.9,101.80,98.50,100.30,100.40,100.80,101.60,100.20,99.40
3,2019.1,100.10,99.9,101.20,98.40,100.30,100.60,100.80,101.60,100.30,100.00
4,2018.12,100.90,101.0,103.80,100.80,100.80,100.70,100.90,101.60,100.40,100.20
5,2018.11,102.70,103.3,109.20,104.60,102.20,100.80,101.10,101.50,100.80,100.10
6,2018.10,103.30,104.2,112.40,106.70,102.50,100.70,100.90,101.20,101.00,99.90
7,2018.9,103.60,104.6,111.70,107.30,102.90,100.80,100.90,101.10,101.10,100.20
8,2018.8,104.10,105.2,112.10,107.80,103.50,100.70,100.70,101.10,101.20,100.20
9,2018.7,104.60,106.0,113.40,109.00,104.10,100.60,100.70,100.70,101.10,99.80
10,2018.6,104.70,106.1,111.50,108.80,104.60,100.40,100.70,100.30,101.10,99.50
11,2018.5,104.10,105.4,108.10,107.40,104.40,100.30,100.30,100.30,101.10,99.30
12,2018.4,103.40,104.5,106.10,105.70,103.90,100.10,100.10,100.20,100.90,99.40
13,2018.3,103.10,104.1,105.00,105.10,103.70,100.20,100.00,100.30,100.90,99.70
14,2018.2,103.70,104.8,106.40,105.90,104.20,100.30,100.00,100.50,101.10,99.90
15,2018.1,104.30,105.7,106.80,107.30,104.90,100.30,100.00,100.80,101.40,99.70
16,2017.12,106.30,106.4,120.67,111.53,106.09,100.65,100.60,101.16,101.32,99.88
17,2017.11,105.80,107.5,110.80,109.70,106.30,100.60,100.40,100.70,101.70,100.00
18,2017.10,106.90,109.0,114.70,111.60,107.50,100.80,100.60,100.90,101.90,100.00
19,2017.9,106.90,109.1,117.20,111.90,107.30,100.70,100.70,101.20,101.30,100.00
20,2017.8,106.40,108.3,118.20,111.00,106.40,100.60,100.70,101.40,100.80,100.00
21,2017.7,105.50,107.3,115.80,109.30,105.80,100.50,100.40,101.20,100.60,100.00
22,2017.6,105.50,107.3,118.30,110.00,105.40,100.50,100.10,101.30,101.00,100.10
23,2017.5,101.00,107.3,122.70,111.10,104.60,100.60,100.30,101.50,101.10,100.20
24,2017.4,101.40,108.4,128.30,113.00,105.20,100.70,100.50,101.50,101.40,99.90
25,2017.3,107.60,110.1,133.70,114.90,106.50,100.70,100.70,101.30,101.40,99.60
26,2017.2,107.80,110.4,136.10,115.50,106.60,100.80,101.10,101.30,101.50,99.40
27,2017.1,106.90,109.1,131.00,112.90,105.90,100.80,101.30,101.10,101.50,99.40
28,2016.12,98.63,107.2,95.40,96.72,98.97,99.96,100.55,100.88,100.04,98.55
29,2016.11,103.30,104.3,114.80,105.80,102.90,100.40,100.90,101.10,100.70,99.00
...,...,...,...,...,...,...,...,...,...,...,...
286,1995.6,113.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,1995.5,113.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,1995.4,117.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,1995.3,119.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,1995.2,120.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,1995.1,120.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,1994.12,119.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,1994.11,119.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,1994.10,118.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,1994.9,118.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,1994.8,118.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,1994.7,120.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,1994.6,119.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,1994.5,120.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,1994.4,119.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,1994.3,117.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,1994.2,116.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,1994.1,118.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,1993.12,122.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,1993.11,122.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
306,1993.10,124.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,1993.9,124.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,1993.8,125.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,1993.7,125.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,1993.6,125.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,1993.5,126.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,1993.4,122.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,1993.3,121.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,1993.2,118.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,1993.1,117.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN